server:
  port: 8080

spring:
  profiles:
    active:
    - local
  application:
    name: local-search-api

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: 
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
   
  data:
    rest:
      base-path: /api/v1
      default-page-size: 10
      max-page-size: 10