server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active:
    - local
  application:
    name: local-search-api

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: 
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

# 404에러 처리를 위한 설정      
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false